<a href="https://colab.research.google.com/github/Sahlegiorgis/DS-Unit-1-Sprint-1-Data-Wrangling-and-Storytelling/blob/master/module_2_LS_DS_121_Statistics_Probability_Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<img align="left" src="https://lever-client-logos.s3.amazonaws.com/864372b1-534c-480e-acd5-9711f850815c-1524247202159.png" width=200>
<br></br>
<br></br>

## *Data Science Unit 1 Sprint 2 Assignment 1*

# Apply the t-test to real data

## Practice 1-Sample T-tests

One Sample t-tests determine whether or not a sample mean is statistically different from some known (or hypothesized) population mean. 

### 1) Load the Data
- Use the [automobile dataset](https://archive.ics.uci.edu/ml/datasets/Automobile)
- Fix the column headers
- Make sure NaNs are used to indicate missing values

Feel free to add code cells and text cells as needed throughout the assignment.

In [ ]:
### YOUR WORK HERE
import pandas as pd
import numpy as np
import seaborn as sns
from matplotlib import style

url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/autos/imports-85.data'

In [ ]:
column_headers = ['symboling','normalized-loss','make-audi',
                          'fuel-type','aspiration', 'num-of-doors',
                          'body-style','drive-wheels',
                          'engine-location','wheel-base','length',
                          'width', 'height', 'curb-weight','engine-type',
                          'num-of-cylinders','engine-size','fuel-system','bore','stroke',
                          'compression-ratio','horsepower','peakrpm','city-mpg','highway-mpg','price']

In [ ]:
df = pd.read_csv('https://archive.ics.uci.edu/ml/machine-learning-databases/autos/imports-85.data', names=column_headers, na_values="?")
df.head()

,symboling,normalized-loss,make-audi,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,length,width,height,curb-weight,engine-type,num-of-cylinders,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peakrpm,city-mpg,highway-mpg,price
0,3,NaN,alfa-romero,gas,std,two,convertible,rwd,front,88.6,168.8,64.1,48.8,2548,dohc,four,130,mpfi,3.47,2.68,9.0,111.0,5000.0,21,27,13495.0
1,3,NaN,alfa-romero,gas,std,two,convertible,rwd,front,88.6,168.8,64.1,48.8,2548,dohc,four,130,mpfi,3.47,2.68,9.0,111.0,5000.0,21,27,16500.0
2,1,NaN,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,171.2,65.5,52.4,2823,ohcv,six,152,mpfi,2.68,3.47,9.0,154.0,5000.0,19,26,16500.0
3,2,164.0,audi,gas,std,four,sedan,fwd,front,99.8,176.6,66.2,54.3,2337,ohc,four,109,mpfi,3.19,3.40,10.0,102.0,5500.0,24,30,13950.0
4,2,164.0,audi,gas,std,four,sedan,4wd,front,99.4,176.6,66.4,54.3,2824,ohc,five,136,mpfi,3.19,3.40,8.0,115.0,5500.0,18,22,17450.0

In [ ]:
df.describe()

,symboling,normalized-loss,wheel-base,length,width,height,curb-weight,engine-size,bore,stroke,compression-ratio,horsepower,peakrpm,city-mpg,highway-mpg,price
count,205.000000,164.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,201.000000,201.000000,205.000000,203.000000,203.000000,205.000000,205.000000,201.000000
mean,0.834146,122.000000,98.756585,174.049268,65.907805,53.724878,2555.565854,126.907317,3.329751,3.255423,10.142537,104.256158,5125.369458,25.219512,30.751220,13207.129353
std,1.245307,35.442168,6.021776,12.337289,2.145204,2.443522,520.680204,41.642693,0.273539,0.316717,3.972040,39.714369,479.334560,6.542142,6.886443,7947.066342
min,-2.000000,65.000000,86.600000,141.100000,60.300000,47.800000,1488.000000,61.000000,2.540000,2.070000,7.000000,48.000000,4150.000000,13.000000,16.000000,5118.000000
25%,0.000000,94.000000,94.500000,166.300000,64.100000,52.000000,2145.000000,97.000000,3.150000,3.110000,8.600000,70.000000,4800.000000,19.000000,25.000000,7775.000000
50%,1.000000,115.000000,97.000000,173.200000,65.500000,54.100000,2414.000000,120.000000,3.310000,3.290000,9.000000,95.000000,5200.000000,24.000000,30.000000,10295.000000
75%,2.000000,150.000000,102.400000,183.100000,66.900000,55.500000,2935.000000,141.000000,3.590000,3.410000,9.400000,116.000000,5500.000000,30.000000,34.000000,16500.000000
max,3.000000,256.000000,120.900000,208.100000,72.300000,59.800000,4066.000000,326.000000,3.940000,4.170000,23.000000,288.000000,6600.000000,49.000000,54.000000,45400.000000

### 2) Pretend that this dataset represents the cars at a used car lot in your local town. 

- Use df.sample() to pick a random sample of 10 cars. Note that because this sample is random we are going to set the `random_state` so that all of us in the class get the same random sample. Please set your random state to `30` when using `df.sample()`

Is your sample reflective of the population value in regards to highway-mpg? Find the mean for `highway-mpg` for the entire dataset and use a 1-sample t-test to compare your estaimated sample mean to the population mean. Can you say that they are different?

In [ ]:
### YOUR WORK HERE
df.sample(30)

     3    ?    alfa-romero     gas    std   two  ...  9.00  111  5000  21  27  13495
128  1    ?        porsche     gas    std   two  ...  10.0  288  5750  17  28      ?
64   0  118          mazda     gas    std  four  ...   8.0  120  5000  19  27  18280
92   1  103         nissan     gas    std  four  ...   9.4   69  5200  31  37   7349
142  0  102         subaru     gas    std  four  ...   9.0   94  5200  26  32   9960
61   0  115          mazda     gas    std  four  ...   8.6   84  4800  26  32  10245
23   1  148          dodge     gas    std  four  ...   9.4   68  5500  31  38   6229
111  0  161         peugot  diesel  turbo  four  ...  21.0   95  4150  28  33  16900
199 -1   95          volvo     gas    std  four  ...   9.5  114  5400  23  28  16845
36   0  106          honda     gas    std   two  ...   9.0   86  5800  27  33   7895
39   0   85          honda     gas    std  four  ...   9.0   86  5800  27  33  10295
83   3    ?     mitsubishi     gas  turbo   two  ...   7.0  145  5000  19  24  14489
35   0   78          honda     gas    std  four  ...   9.2   76  6000  30  34   7295
44   0    ?          isuzu     gas    std  four  ...   9.6   70  5400  38  43      ?
79   3  153     mitsubishi     gas  turbo   two  ...   7.5  116  5500  23  30   9959
66  -1   93  mercedes-benz  diesel  turbo  four  ...  21.5  123  4350  22  25  25552
160  0   91         toyota     gas    std  four  ...   9.0   70  4800  28  34   8358
159  0   91         toyota     gas    std  four  ...   9.0   70  4800  38  47   7738
125  3    ?        porsche     gas    std   two  ...   9.5  207  5900  17  25  32528
170  2  134         toyota     gas    std   two  ...   9.3  116  4800  24  30  11549
59   0  115          mazda     gas    std  four  ...   8.6   84  4800  26  32   8495
30   2  137          honda     gas    std   two  ...   9.2   76  6000  31  38   6855
176 -1   65         toyota     gas    std  four  ...   8.7   92  4200  27  32  11248
193 -2  103          volvo     gas    std  four  ...   9.5  114  5400  23  28  12940
154  0   91         toyota     gas    std  four  ...   9.0   62  4800  27  32   8778
77   2  161     mitsubishi     gas    std   two  ...   9.4   68  5500  31  38   6669
179 -1   90         toyota     gas    std  four  ...   9.2  156  5200  20  24  15690
101  0  108         nissan     gas    std  four  ...   9.0  152  5200  17  22  14399
38   0   85          honda     gas    std  four  ...   9.0   86  5800  27  33   8845
189  3  256     volkswagen     gas    std   two  ...   8.5   90  5500  24  29   9980
164  1  168         toyota     gas    std   two  ...   9.4  112  6600  26  29   9298

[30 rows x 26 columns]

The salesman says the cars he sells typically have a fuel efficiency of about 35 miles per gallon on the highway. You want to verify his claim but can only test 10 cars. Using your sample of 10, test his claim and report your results.

In [ ]:
### YOUR WORK HERE
# t_df10 = np.random.standard_t(df=10, size=10)
df.sample(10)

     3    ? alfa-romero     gas    std   two  ...  9.00  111  5000  21  27  13495
191  0    ?  volkswagen  diesel  turbo  four  ...  23.0   68  4500  33  38  13845
151  1   74      toyota     gas    std  four  ...   9.0   62  4800  31  38   6488
171  2  134      toyota     gas    std   two  ...   9.3  116  4800  24  30  17669
120  1  154    plymouth     gas    std  four  ...   9.4   68  5500  31  38   6692
46   0  145      jaguar     gas    std  four  ...   8.1  176  4750  15  19  32250
44   0    ?       isuzu     gas    std  four  ...   9.6   70  5400  38  43      ?
85   1  125  mitsubishi     gas    std  four  ...   8.5   88  5000  25  32   8189
15   0    ?         bmw     gas    std   two  ...   8.0  182  5400  16  22  41315
149  1   87      toyota     gas    std   two  ...   9.0   62  4800  35  39   5348
78   1  161  mitsubishi     gas  turbo   two  ...   7.6  102  5500  24  30   7689

[10 rows x 26 columns]

In [ ]:
df.sample().mean()

3            0.00
88.60       94.50
168.80     155.90
64.10       63.60
48.80       52.00
2548      1909.00
130         90.00
3.47         3.03
2.68         3.11
9.00         9.60
111         70.00
5000      5400.00
21          38.00
27          43.00
dtype: float64

In [ ]:
# sns.kdeplot(t_df10, color='r');
import numpy as np
from scipy import stats

In [ ]:
## Import the packages
import numpy as np
from scipy import stats


## Define 2 random distributions
#Sample Size
N = 10
#Gaussian distributed data with mean = 2 and var = 1
a = np.random.randn(N) + 2
#Gaussian distributed data with with mean = 0 and var = 1
b = np.random.randn(N)


## Calculate the Standard Deviation
#Calculate the variance to get the standard deviation

#For unbiased max likelihood estimate we have to divide the var by N-1, and therefore the parameter ddof = 1
var_a = a.var(ddof=1)
var_b = b.var(ddof=1)

#std deviation
s = np.sqrt((var_a + var_b)/2)
s



## Calculate the t-statistics
t = (a.mean() - b.mean())/(s*np.sqrt(2/N))



## Compare with the critical t-value
#Degrees of freedom
df = 2*N - 2

#p-value after comparison with the t 
p = 1 - stats.t.cdf(t,df=df)


print("t = " + str(t))
print("p = " + str(2*p))
### You can see that after comparing the t statistic with the critical t value (computed internally) we get a good p value of 0.0005 and thus we reject the null hypothesis and thus it proves that the mean of the two distributions are different and statistically significant.


## Cross Checking with the internal scipy function
t2, p2 = stats.ttest_ind(a,b)
print("t = " + str(t2))
print("p = " + str(p2))

In [ ]:
from scipy.stats import ttest_ind
import numpy as np
t_df10 = np.random.standard_(df=10, size=10)

AttributeError: ignored

Imagine that you now have the capacity to test 100 cars on the lot. Using the same random state of `30`, take a sample of 100 cars. Run a t-test to verify the salesman's claim with your new larger sample. Do you reach the same conclusion as you did with the sample size of 10?

In [ ]:
### YOUR WORK HERE

Why might these two t-tests using the same dataset lead to different conclusions about the salesman's claim?

## Practice 2-Sample T-tests

Two Sample t-tests determine whether or not two sample means are statistically different from each other. 

This portion of your assignment requires you to determine which issues have "statistically significant" differences between political parties in this [1980s congressional voting data](https://archive.ics.uci.edu/ml/datasets/Congressional+Voting+Records).

### 1) Load the data

The data consists of 435 instances (one for each congressperson), a class (democrat or republican), and 16 binary attributes (yes or no for voting for or against certain issues). Be aware - there are missing values!

- Read the dataset in from UCI, you'll need to provide a list of column headers
- Encode "yes" votes as 1 and "no" votes as 0. (You can use `df.replace()` to swap out these values)
- Use dataframe filtering to split the dataframe into two new dataframes based on party. Hold all republicans in one dataframe and all democrats in the other. These will be our two different "samples."

In [ ]:
### YOUR WORK HERE

### 2) Perform two sample T-tests on different issues and report the results.

- Find an issue that democrats support more than republicans with p < 0.01 (significant at the 99% level).
- Find an issue that republicans support more than democrats with p < 0.01 (significant at the 99% level).
- Find an issue where the difference between republicans and democrats has p > 0.1 (Not significant at the 90% level - i.e. there may not be much of a difference the two sample means)

Please for each test that you run state your null and alternative hypothesis and then write a conclusion reflecting on the null and alternative hypothesis.

Remember, that two-sample t-tests will only tell us if the two groups are *different* from one another. We'll have to look at their sample means directly or use the sign on the t-statistic to know which of the two sample means is larger.

In [ ]:
### YOUR WORK HERE

## Stretch Goals:

### 1) Use functions and some iterator (for loop, .apply(), list comprehension, etc.) to perform two sample t-tests on every issue in the dataset in an automated fashion.

In [ ]:
### YOUR WORK HERE



### 2) Work on Performing a T-test without using Scipy in order to get "under the hood" and learn more thoroughly about this topic.
### Start with a 1-sample t-test
 - Establish the conditions for your test 
 - [Calculate the T Statistic](https://blog.minitab.com/hs-fs/hubfs/Imported_Blog_Media/701f9c0efa98a38fb397f3c3ec459b66.png?width=247&height=172&name=701f9c0efa98a38fb397f3c3ec459b66.png) (You'll need to omit NaN values from your sample).
 - Translate that t-statistic into a P-value. You can use a [table](https://www.google.com/search?q=t+statistic+table) or the [University of Iowa Applet](https://homepage.divms.uiowa.edu/~mbognar/applets/t.html)

### Be sure to check your work using Scipy!

In [ ]:
### YOUR WORK HERE

### 3) Then try a 2-sample t-test
 - Establish the conditions for your test 
 - [Calculate the T Statistic](https://lh3.googleusercontent.com/proxy/rJJ5ZOL9ZDvKOOeBihXoZDgfk7uv1YsRzSQ1Tc10RX-r2HrRpRLVqlE9CWX23csYQXcTniFwlBg3H-qR8MKJPBGnjwndqlhDX3JxoDE5Yg) (You'll need to omit NaN values from your sample).
 - Translate that t-statistic into a P-value. You can use a [table](https://www.google.com/search?q=t+statistic+table) or the [University of Iowa Applet](https://homepage.divms.uiowa.edu/~mbognar/applets/t.html)

 ### Be sure to check your work using Scipy!

In [ ]:
### YOUR WORK HERE